// -------------------------------------------------------------------------
// FILE: PitWallLanguage.cs
// VERSION: V0.12.00 (Neural Voice Engine & Multi-language)
// -------------------------------------------------------------------------
using System.Collections.Generic;

namespace SimRIG
{
    public static class PitWallLanguage
    {
        private static readonly Dictionary<string, Dictionary<string, string>> Dictionary = new Dictionary<string, Dictionary<string, string>>
        {
            { "EN", new Dictionary<string, string> {
                { "TARGET_NO_CAR", "Nothing to report right now, man." },
                                { "REPORT_GAP_0", "{0} is ahead of us. Gap is around {1} seconds." },
                { "REPORT_GAP_1", "We have {0} in front. The gap is currently {1} seconds." },
                { "REPORT_GAP_2", "{0} is in front of us. Gap is about {1} seconds." },
                { "REPORT_GAP_3", "Chasing {0} ahead. The gap is {1} seconds." },
                { "REPORT_FULL_0", "{0} is ahead of us. Gap is around {1} seconds... and looking at the data, I'd say he is {2}." },
                { "REPORT_FULL_1", "We have {0} in front. The gap is currently {1} seconds... and it looks like he is {2}." },
                { "REPORT_FULL_2", "{0} is in front of us. Gap is about {1} seconds... and from our data, I'd say he is {2}." },
                { "REPORT_FULL_3", "Chasing {0} ahead. The gap is {1} seconds... and it seems he is {2}." },
                { "REPORT_UNDERCUT", "...we should definitely consider the undercut here, we can jump him." },
                { "REPORT_NO_UNDERCUT", "...but it's a bit too early for an undercut, let's track him for now." },
                { "AUTO_UNDERCUT_ALERT", "Listen, {0} is inside our undercut window. If we pit now, we can jump him. Think about it." },
                { "CONFIRM_FULL", "Copy that. Confirmed {0} liters and 4 fresh tyres." },
                { "CONFIRM_2TYRES", "Copy that. Confirmed {0} liters and 2 fresh tyres." },
                { "CONFIRM_1TYRE", "Copy that. Confirmed {0} liters and 1 fresh tyre." },
                { "CONFIRM_FUEL", "Copy, just fuel. Adding {0} liters, tyres stay as they are." },
                { "CONFIRM_PRESS", "Copy, pressures adjusted. Sending the offsets to the crew." },
                { "CONFIRM_CLEAR", "Got it, pit options cleared." },
                { "FUEL_TARGET_ALERT", "We are over-consuming on our target burn. Remember to lift earlier." },
                { "FUEL_TARGET_OK", "Nice job, fuel saving is exactly where we want it." },
                { "RAW_SPEECH", "{0}" },
                
                { "DROP_ZONE_INFO", "Pit loss is {0} seconds. Drop zone is {1}." },
                { "BOX_NOW", "Fuel is low. We are going to box at the end of this lap." },
                { "PIT_EXIT_TRAFFIC", "Careful on exit, we have traffic coming up." },
                { "ZONE_CLEAR", "clear" },
                { "ZONE_1CAR", "one car" },
                { "ZONE_TRAFFIC", "heavy traffic" },
                { "CALIB_FUEL_REQ", "We need some extra data for our calculations. Set Tyres to NONE, add at least ten litres of fuel, then pit" },
                { "CALIB_TYRE_REQ", "We need some extra data for our calculations, please set Tyres on ALL4, then perform a PitStop" },
                { "CALIB_DT_REQ", "We need some more data for our strategy calculations, please perform a DriveThrough" },
                { "CALIB_SG_REQ", "We need some extra data for our strategy, perform a stop and go" },
                { "CALIB_NEED_LAP", "Before we calibrate, head out and complete a full lap" },
                { "CALIB_TYRE_HALF_REQ", "Now set tyres to two only, either an axle or a side, and pit again with no fuel" },
                { "CALIB_TYRE_SINGLE_REQ", "Last one: set a single tyre, no fuel, and pit" },
                { "CALIB_COMPLETE", "Calibration complete, all data collected. We are ready to race" },
                
                { "DIAG_PUSHING", "pushing quite hard" },
                { "DIAG_FUELSAVING", "definitely saving fuel" },
                { "DIAG_TIREWEAR", "struggling with his tyres" },
                { "DIAG_STABLE", "holding a steady pace" },
                { "DIAG_CONSERVING", "conserving his pace" },
                { "DIAG_ANALYZING", "analyzing pace" },

                // Nuove chiavi strategiche e interattive
                { "PIT_EXIT_TRAFFIC_ALERT", "Careful on exit, we'll merge into traffic! Car is {0} seconds away." },
                { "PIT_EXIT_CLEAR", "Pit exit is clear, clean track, push now!" },
                { "TARGET_ENTERING_PITS", "Our target {0} is pitting now." },
                { "TARGET_ENTERING_PITS_OVERCUT", "Our target {0} is pitting. Overcut is viable, push hard on this lap!" },
                { "WET_OPPONENTS_ENTERING_PITS", "Opponents are entering the pitbox. Let's monitor their pace on exit." },
                { "RAIN_ALERT", "Humidity at {0}% and pressure dropping. With wind at {1} meters per second, rain is expected in about {2} laps." },
                { "TARGET_EXITED_PITS_BEHIND", "Great job! {0} exited the pits behind us." },
                { "TARGET_EXITED_PITS_AHEAD", "{0} exited the pits ahead of us." },
                { "PIT_WINDOW_ALERT", "Pit window is open. Do you confirm tyres and fuel?" },
                { "CONFIRM_INTERACTIVE_FUEL", "Copy that, just fuel. Tyres will stay as they are." },
                { "CONFIRM_INTERACTIVE_TYRES", "Copy, tyres only. No fuel addition." },
                { "CONFIRM_INTERACTIVE_BOTH", "Copy that, full service. Tyres and fuel confirmed." },
                { "SANITY_CHECK_PIT_NOT_SET", "Caution, we are heading into the pits but options are not configured." },
                                { "CONFIRM_JUST_TYRES_NONE", "Perfect, glad to know you're managing it." },
                { "PIT_WINDOW_ASK_TYRES", "Pit window is open. Let me know how your tyres are doing." },
                { "CORNER_FL", "front left" },
                { "CORNER_FR", "front right" },
                { "CORNER_RL", "rear left" },
                { "CORNER_RR", "rear right" },
                { "CONFIRM_TYRES_ALL4_0", "Copy, we'll prepare 4 new tyres for the next stint." },
                { "CONFIRM_TYRES_ALL4_1", "Ok, we'll get your tyres ready." },
                { "CONFIRM_TYRES_FRONTS_0", "Copy, we'll prepare 2 fronts for your next stint." },
                { "CONFIRM_TYRES_FRONTS_1", "Ok, we'll swap the front tyres." },
                { "CONFIRM_TYRES_REARS_0", "Copy, we'll prepare 2 rears for your next stint." },
                { "CONFIRM_TYRES_REARS_1", "Ok, we'll swap the rear tyres." },
                { "CONFIRM_TYRES_LEFT_0", "Copy, we'll prepare 2 lefts for your next stint." },
                { "CONFIRM_TYRES_LEFT_1", "Ok, we'll swap the left tyres." },
                { "CONFIRM_TYRES_RIGHT_0", "Copy, we'll prepare 2 rights for your next stint." },
                { "CONFIRM_TYRES_RIGHT_1", "Ok, we'll swap the right tyres." },
                { "CONFIRM_TYRES_SINGLE_0", "Copy, we'll replace the {0} tyre for your next stint." },
                { "CONFIRM_TYRES_SINGLE_1", "Ok, we'll swap the {0} tyre." },{ "FUEL_WARNING_LIFT_COAST", "Warning, our fuel is critical. If we don't start saving now, we won't finish the race. Lift and coast." },
                { "FORMATION_LAP_START", "Ok {0}, hold your position in the formation lap. Let's make it a clean race." },
                { "FORMATION_LAP_GRID", "Almost there, green flag is about to wave, get ready." },
                { "CROSSOVER_BOX_WETS", "Wet tires are now faster than our slicks by {0} seconds. Box recommended for Wets." },
                { "CROSSOVER_BOX_SLICKS", "Slick tires are now faster than our wets by {0} seconds. Box recommended for Slicks." },
                { "CONFIRM_WET", "Wet compound selected." },
                { "CONFIRM_DRY", "Slick compound selected." },
            }},
            { "IT", new Dictionary<string, string> {
                { "TARGET_NO_CAR", "Nulla da segnalare al momento." },
                                { "REPORT_GAP_0", "{0} è davanti a noi. Il distacco è di circa {1} secondi." },
                { "REPORT_GAP_1", "Abbiamo {0} davanti. Il gap al momento è di {1} secondi." },
                { "REPORT_GAP_2", "Davanti a noi c'è {0}. Il distacco è intorno ai {1} secondi." },
                { "REPORT_GAP_3", "Stiamo inseguendo {0} davanti. Il gap è di {1} secondi." },
                { "REPORT_FULL_0", "{0} è davanti a noi. Il distacco è di circa {1} secondi... e dai dati direi che {2}." },
                { "REPORT_FULL_1", "Abbiamo {0} davanti. Il gap al momento è di {1} secondi... e sembra che {2}." },
                { "REPORT_FULL_2", "Davanti a noi c'è {0}. Il distacco è intorno ai {1} secondi... e dai nostri dati direi che {2}." },
                { "REPORT_FULL_3", "Stiamo inseguendo {0} davanti. Il gap è di {1} secondi... e sembra che stia {2}." },
                { "REPORT_UNDERCUT", "...valutiamo l'undercut adesso, possiamo passargli davanti." },
                { "REPORT_NO_UNDERCUT", "...però è presto per l'undercut, continuiamo a mollarlo così." },
                { "AUTO_UNDERCUT_ALERT", "Senti, {0} è nella nostra finestra di undercut. Se ci fermiamo adesso gli usciamo davanti. Pensaci." },
                { "CONFIRM_FULL", "Ricevuto. Confermati {0} litri e 4 gomme nuove." },
                { "CONFIRM_2TYRES", "Ricevuto. Confermati {0} litri e 2 gomme nuove." },
                { "CONFIRM_1TYRE", "Ricevuto. Confermati {0} litri e 1 gomma nuova." },
                { "CONFIRM_FUEL", "Ricevuto, solo benzina. Mettiamo {0} litri, niente gomme." },
                { "CONFIRM_PRESS", "Ricevuto, pressioni regolate. Invio i dati ai meccanici." },
                { "CONFIRM_CLEAR", "Ok, impostazioni pit azzerate." },
                { "FUEL_TARGET_ALERT", "Siamo sopra il consumo target. Ricordati di alzare il piede prima." },
                { "FUEL_TARGET_OK", "Ottimo lavoro, la gestione benzina è perfetta." },
                { "RAW_SPEECH", "{0}" },
                
                { "DROP_ZONE_INFO", "Tempo perso stimato {0} secondi. La zona di rientro è {1}." },
                { "BOX_NOW", "Carburante in esaurimento. Rientriamo ai box alla fine di questo giro." },
                { "PIT_EXIT_TRAFFIC", "Attenzione in uscita, traffico in arrivo." },
                { "ZONE_CLEAR", "libera" },
                { "ZONE_1CAR", "una vettura" },
                { "ZONE_TRAFFIC", "traffico pesante" },
                { "CALIB_FUEL_REQ", "Ci servono dati per i calcoli. Imposta le gomme su NESSUNA, aggiungi almeno dieci litri di benzina, poi fermati ai box" },
                { "CALIB_TYRE_REQ", "Ci servono dati per i calcoli, imposta le gomme su ALL4 e fai un pit stop" },
                { "CALIB_DT_REQ", "Ci servono più dati per i calcoli della strategia, per favore esegui un DriveThrough" },
                { "CALIB_SG_REQ", "Ci servono dati extra per la strategia, esegui uno stop and go" },
                { "CALIB_NEED_LAP", "Prima di calibrare, esci in pista e completa un giro" },
                { "CALIB_TYRE_HALF_REQ", "Ora imposta due gomme sole, un asse o un lato, e rientra ai box senza benzina" },
                { "CALIB_TYRE_SINGLE_REQ", "Ultima: imposta una gomma sola, niente benzina, e rientra" },
                { "CALIB_COMPLETE", "Calibrazione completata, abbiamo tutti i dati. Siamo pronti per la gara" },
                
                { "DIAG_PUSHING", "sta spingendo forte" },
                { "DIAG_FUELSAVING", "sta decisamente gestendo la benzina" },
                { "DIAG_TIREWEAR", "è un po' in crisi con le gomme" },
                { "DIAG_STABLE", "ha un passo molto stabile" },
                { "DIAG_CONSERVING", "sta conservando la vettura" },
                { "DIAG_ANALYZING", "stiamo ancora raccogliendo dati" },

                // Nuove chiavi strategiche e interattive
                { "PIT_EXIT_TRAFFIC_ALERT", "Attenzione in uscita, rientriamo nel traffico! C'è una vettura a {0} secondi." },
                { "PIT_EXIT_CLEAR", "Uscita box libera, pista pulita, spingi!" },
                { "TARGET_ENTERING_PITS", "Il nostro bersaglio {0} è rientrato ai box." },
                { "TARGET_ENTERING_PITS_OVERCUT", "Il nostro bersaglio {0} è rientrato ai box. L'overcut è viabile, spingi forte in questo giro!" },
                { "WET_OPPONENTS_ENTERING_PITS", "I nostri avversari stanno entrando ai box per cambiare gomme. Monitoriamo il loro passo all'uscita." },
                { "RAIN_ALERT", "Umidità al {0}% e pressione in calo. Con il vento a {1} metri al secondo, la pioggia è attesa tra circa {2} giri." },
                { "TARGET_EXITED_PITS_BEHIND", "Ottimo lavoro! {0} è uscito dai box dietro di noi." },
                { "TARGET_EXITED_PITS_AHEAD", "{0} è uscito dai box davanti a noi." },
                { "PIT_WINDOW_ALERT", "Finestra di sosta aperta. Confermiamo cambio gomme e benzina?" },
                { "CONFIRM_INTERACTIVE_FUEL", "Ricevuto, solo benzina. Le gomme rimangono come sono." },
                { "CONFIRM_INTERACTIVE_TYRES", "Ricevuto, solo gomme. Niente rifornimento benzina." },
                { "CONFIRM_INTERACTIVE_BOTH", "Ricevuto, sosta completa. Gomme e benzina confermate." },
                { "SANITY_CHECK_PIT_NOT_SET", "Attenzione, stiamo entrando ai box ma le opzioni di sosta non sono configurate." },
                                { "CONFIRM_JUST_TYRES_NONE", "Perfetto, mi fa piacere sapere che le stai gestendo." },
                { "PIT_WINDOW_ASK_TYRES", "Finestra dei box aperta. Fammi sapere come vanno le gomme." },
                { "CORNER_FL", "anteriore sinistra" },
                { "CORNER_FR", "anteriore destra" },
                { "CORNER_RL", "posteriore sinistra" },
                { "CORNER_RR", "posteriore destra" },
                { "CONFIRM_TYRES_ALL4_0", "Ricevuto, prepareremo 4 gomme nuove per il prossimo stint." },
                { "CONFIRM_TYRES_ALL4_1", "Ok, prepariamo le gomme." },
                { "CONFIRM_TYRES_FRONTS_0", "Ricevuto, prepareremo 2 anteriori per il prossimo stint." },
                { "CONFIRM_TYRES_FRONTS_1", "Ok, cambiamo le anteriori." },
                { "CONFIRM_TYRES_REARS_0", "Ricevuto, prepareremo 2 posteriori per il prossimo stint." },
                { "CONFIRM_TYRES_REARS_1", "Ok, cambiamo le posteriori." },
                { "CONFIRM_TYRES_LEFT_0", "Ricevuto, prepareremo 2 sinistre per il prossimo stint." },
                { "CONFIRM_TYRES_LEFT_1", "Ok, cambiamo le sinistre." },
                { "CONFIRM_TYRES_RIGHT_0", "Ricevuto, prepareremo 2 destre per il prossimo stint." },
                { "CONFIRM_TYRES_RIGHT_1", "Ok, cambiamo le destre." },
                { "CONFIRM_TYRES_SINGLE_0", "Ricevuto, sostituiremo la gomma {0} per il prossimo stint." },
                { "CONFIRM_TYRES_SINGLE_1", "Ok, cambiamo la gomma {0}." },{ "FUEL_WARNING_LIFT_COAST", "Attenzione, la benzina è critica. Se non iniziamo a risparmiare ora, non finiremo la gara. Alza il piede." },
                { "FORMATION_LAP_START", "Ok {0}, tieni la tua posizione nel formation lap. Cerchiamo di fare una gara pulita." },
                { "FORMATION_LAP_GRID", "Ci siamo quasi, tra poco scatterà la bandiera verde, tieniti pronto." },
                { "CROSSOVER_BOX_WETS", "Le gomme da bagnato sono ora più veloci delle nostre slick di {0} secondi. Consigliato entrare ai box per montare le Wet." },
                { "CROSSOVER_BOX_SLICKS", "Le gomme slick sono ora più veloci delle nostre wet di {0} secondi. Consigliato entrare ai box per montare le Slick." },
                { "CONFIRM_WET", "Impostate gomme da bagnato." },
                { "CONFIRM_DRY", "Impostate gomme slick." },
            }},
            { "DE", new Dictionary<string, string> {
                { "TARGET_NO_CAR", "Zurzeit gibt es nichts zu berichten." },
                                { "REPORT_GAP_0", "{0} liegt vor uns. Der Abstand beträgt etwa {1} Sekunden." },
                { "REPORT_GAP_1", "Wir haben {0} vor uns. Die Lücke ist aktuell {1} Sekunden." },
                { "REPORT_GAP_2", "{0} ist vor uns. Der Abstand liegt bei circa {1} Sekunden." },
                { "REPORT_GAP_3", "Wir jagen {0} da vorne. Der Abstand beträgt {1} Sekunden." },
                { "REPORT_FULL_0", "{0} liegt vor uns. Der Abstand beträgt etwa {1} Sekunden... und den Daten nach {2}." },
                { "REPORT_FULL_1", "Wir haben {0} vor uns. Die Lücke ist aktuell {1} Sekunden... und es sieht so aus, als ob er {2}." },
                { "REPORT_FULL_2", "{0} ist vor uns. Der Abstand liegt bei circa {1} Sekunden... und nach unseren Daten {2}." },
                { "REPORT_FULL_3", "Wir jagen {0} da vorne. Der Abstand beträgt {1} Sekunden... und es scheint, er {2}." },
                { "REPORT_UNDERCUT", "...wir sollten hier auf jeden Fall den Undercut in Betracht ziehen, wir können ihn schnappen." },
                { "REPORT_NO_UNDERCUT", "...aber es ist noch zu früh für einen Undercut, bleiben wir erst mal dran." },
                { "AUTO_UNDERCUT_ALERT", "Hör zu, {0} ist in unserem Undercut-Fenster. Wenn wir jetzt stoppen, kommen wir vor ihm raus. Denk drüber nach." },
                { "CONFIRM_FULL", "Verstanden. Bestätigt {0} Liter und 4 neue Reifen." },
                { "CONFIRM_2TYRES", "Verstanden. Bestätigt {0} Liter und 2 neue Reifen." },
                { "CONFIRM_1TYRE", "Verstanden. Bestätigt {0} Liter und 1 neuer Reifen." },
                { "CONFIRM_FUEL", "Kopie, nur Kraftstoff. Wir füllen {0} Liter nach, keine Reifen." },
                { "CONFIRM_PRESS", "Verstanden, Reifendruck angepasst. Sende die Daten an die Crew." },
                { "CONFIRM_CLEAR", "Ok, Boxenstopp-Optionen zurückgesetzt." },
                { "FUEL_TARGET_ALERT", "Wir verbrauchen mehr als unser Ziel. Denk ans Lift and Coast." },
                { "FUEL_TARGET_OK", "Gute Arbeit, Kraftstoffverbrauch ist genau im Ziel." },
                { "RAW_SPEECH", "{0}" },
                
                { "DROP_ZONE_INFO", "Zeitverlust in der Box ist {0} Sekunden. Rückkehrzone ist {1}." },
                { "BOX_NOW", "Kraftstoff geht zur Neige. Wir stoppen am Ende dieser Runde." },
                { "PIT_EXIT_TRAFFIC", "Achtung bei der Ausfahrt, wir haben Verkehr." },
                { "ZONE_CLEAR", "frei" },
                { "ZONE_1CAR", "ein Fahrzeug" },
                { "ZONE_TRAFFIC", "starker Verkehr" },
                { "CALIB_FUEL_REQ", "Wir brauchen Daten für die Berechnungen. Stelle Reifen auf KEINE, tanke mindestens zehn Liter, dann komm an die Box." },
                { "CALIB_TYRE_REQ", "Wir brauchen Daten für die Berechnungen. Bitte stelle Reifen auf ALL4 und mache einen Boxenstopp." },
                { "CALIB_DT_REQ", "Wir benötigen mehr Daten für die Strategie. Bitte mache eine Durchfahrtsstrafe." },
                { "CALIB_SG_REQ", "Wir brauchen extra Daten für die Strategie. Bitte mache einen Stop-and-Go." },
                { "CALIB_NEED_LAP", "Bevor wir kalibrieren, fahr raus und beende eine volle Runde" },
                { "CALIB_TYRE_HALF_REQ", "Jetzt nur zwei Reifen, eine Achse oder eine Seite, und komm ohne Kraftstoff an die Box" },
                { "CALIB_TYRE_SINGLE_REQ", "Zum Schluss: ein einzelner Reifen, kein Kraftstoff, und an die Box" },
                { "CALIB_COMPLETE", "Kalibrierung abgeschlossen, alle Daten erfasst. Wir sind bereit" },
                
                { "DIAG_PUSHING", "pusht ziemlich hart" },
                { "DIAG_FUELSAVING", "spart definitiv Kraftstoff" },
                { "DIAG_TIREWEAR", "hat Probleme mit seinen Reifen" },
                { "DIAG_STABLE", "hält eine konstante Pace" },
                { "DIAG_CONSERVING", "schont sein Fahrzeug" },
                { "DIAG_ANALYZING", "analysieren Pace" },

                // Nuove chiavi strategiche e interattive
                { "PIT_EXIT_TRAFFIC_ALERT", "Achtung bei der Ausfahrt, wir kommen im Verkehr raus! Ein Auto ist {0} Sekunden entfernt." },
                { "PIT_EXIT_CLEAR", "Boxenausfahrt ist frei, freie Bahn, jetzt pushen!" },
                { "TARGET_ENTERING_PITS", "Unser Ziel {0} biegt jetzt in die Boxengasse ab." },
                { "TARGET_ENTERING_PITS_OVERCUT", "Unser Ziel {0} biegt in die Box ab. Overcut ist machbar, gib jetzt alles in dieser Runde!" },
                { "WET_OPPONENTS_ENTERING_PITS", "Gegner biegen in die Boxengasse ab. Lasst uns ihr Tempo nach der Ausfahrt beobachten." },
                { "RAIN_ALERT", "Feuchtigkeit bei {0}% und Luftdruck sinkt. Mit Wind bei {1} Metern pro Sekunde wird der Regen in etwa {2} Runden erwartet." },
                { "TARGET_EXITED_PITS_BEHIND", "Gute Arbeit! {0} ist hinter uns aus der Box gekommen." },
                { "TARGET_EXITED_PITS_AHEAD", "{0} ist vor uns aus der Box gekommen." },
                { "PIT_WINDOW_ALERT", "Boxenstopp-Fenster ist offen. Bestätigen wir Reifen und Kraftstoff?" },
                { "CONFIRM_INTERACTIVE_FUEL", "Verstanden, nur Kraftstoff. Reifen bleiben wie sie sind." },
                { "CONFIRM_INTERACTIVE_TYRES", "Verstanden, nur Reifen. Kein Kraftstoff nachtanken." },
                { "CONFIRM_INTERACTIVE_BOTH", "Verstanden, kompletter Service. Reifen und Kraftstoff bestätigt." },
                { "SANITY_CHECK_PIT_NOT_SET", "Achtung, wir fahren in die Box, aber die Stopp-Optionen sind nicht konfiguriert." },
                                { "CONFIRM_JUST_TYRES_NONE", "Perfekt, schön zu hören, dass du damit klarkommst." },
                { "PIT_WINDOW_ASK_TYRES", "Boxenstopp-Fenster ist offen. Lass mich wissen, wie es deinen Reifen geht." },
                { "CORNER_FL", "vorne links" },
                { "CORNER_FR", "vorne rechts" },
                { "CORNER_RL", "hinten links" },
                { "CORNER_RR", "hinten rechts" },
                { "CONFIRM_TYRES_ALL4_0", "Verstanden, wir bereiten 4 neue Reifen für den nächsten Stint vor." },
                { "CONFIRM_TYRES_ALL4_1", "Ok, wir machen deine Reifen bereit." },
                { "CONFIRM_TYRES_FRONTS_0", "Verstanden, wir bereiten 2 Vorderreifen für den nächsten Stint vor." },
                { "CONFIRM_TYRES_FRONTS_1", "Ok, wir wechseln die Vorderreifen." },
                { "CONFIRM_TYRES_REARS_0", "Verstanden, wir bereiten 2 Hinterreifen für den nächsten Stint vor." },
                { "CONFIRM_TYRES_REARS_1", "Ok, wir wechseln die Hinterreifen." },
                { "CONFIRM_TYRES_LEFT_0", "Verstanden, wir bereiten 2 linke Reifen für den nächsten Stint vor." },
                { "CONFIRM_TYRES_LEFT_1", "Ok, wir wechseln die linken Reifen." },
                { "CONFIRM_TYRES_RIGHT_0", "Verstanden, wir bereiten 2 rechte Reifen für den nächsten Stint vor." },
                { "CONFIRM_TYRES_RIGHT_1", "Ok, wir wechseln die rechten Reifen." },
                { "CONFIRM_TYRES_SINGLE_0", "Verstanden, wir ersetzen den Reifen {0} für den nächsten Stint." },
                { "CONFIRM_TYRES_SINGLE_1", "Ok, wir wechseln den Reifen {0}." },{ "FUEL_WARNING_LIFT_COAST", "Achtung, Kraftstoff ist kritisch. Wenn wir jetzt nicht sparen, kommen wir nicht ins Ziel. Lift and coast." },
                { "FORMATION_LAP_START", "Ok {0}, halte deine Position in der Einführungsrunde. Lass uns ein sauberes Rennen fahren." },
                { "FORMATION_LAP_GRID", "Fast da, die grüne Flagge wird gleich geschwenkt, mach dich bereit." },
                { "CROSSOVER_BOX_WETS", "Regenreifen sind jetzt um {0} Sekunden schneller als unsere Slicks. Boxenstopp für Wets empfohlen." },
                { "CROSSOVER_BOX_SLICKS", "Slicks sind jetzt um {0} Sekunden schneller als unsere Regenreifen. Boxenstopp für Slicks empfohlen." },
                { "CONFIRM_WET", "Regenreifen ausgewählt." },
                { "CONFIRM_DRY", "Slicks ausgewählt." },
            }},
            { "ES", new Dictionary<string, string> {
                { "TARGET_NO_CAR", "Nada que reportar por ahora." },
                                { "REPORT_GAP_0", "{0} está delante de nosotros. La distancia es de unos {1} segundos." },
    { "REPORT_GAP_1", "Tenemos a {0} delante. El margen es actualmente de {1} segundos." },
    { "REPORT_GAP_2", "{0} está por delante. La distancia es de aproximadamente {1} segundos." },
    { "REPORT_GAP_3", "Persiguiendo a {0} delante. La brecha es de {1} segundos." },
    { "REPORT_FULL_0", "{0} está delante de nosotros. La distancia es de unos {1} segundos... y según los datos diría que {2}." },
    { "REPORT_FULL_1", "Tenemos a {0} delante. El margen es actualmente de {1} segundos... y parece que {2}." },
    { "REPORT_FULL_2", "{0} está por delante. La distancia es de aproximadamente {1} segundos... y según nuestros datos diría que {2}." },
    { "REPORT_FULL_3", "Persiguiendo a {0} delante. La brecha es de {1} segundos... y parece que está {2}." },
                { "REPORT_UNDERCUT", "...sin duda deberíamos considerar el undercut aquí, podemos pasarle." },
                { "REPORT_NO_UNDERCUT", "...pero es pronto para el undercut, sigamos así de momento." },
                { "AUTO_UNDERCUT_ALERT", "Oye, {0} está en nuestra ventana de undercut. Si paramos ahora salimos por delante. Piénsalo." },
                { "CONFIRM_FULL", "Recibido. Confirmados {0} litros y 4 neumáticos nuevos." },
                { "CONFIRM_2TYRES", "Recibido. Confirmados {0} litros y 2 neumáticos nuevos." },
                { "CONFIRM_1TYRE", "Recibido. Confirmados {0} litros y 1 neumático nuevo." },
                { "CONFIRM_FUEL", "Recibido, solo gasolina. Ponemos {0} litros, sin cambiar neumáticos." },
                { "CONFIRM_PRESS", "Recibido, presiones ajustadas. Envío los datos a los mecánicos." },
                { "CONFIRM_CLEAR", "Entendido, opciones de parada borradas." },
                { "FUEL_TARGET_ALERT", "Consumo por encima del objetivo. Recuerda levantar el pie antes." },
                { "FUEL_TARGET_OK", "Buen trabajo, la gestión del combustible es perfecta." },
                { "RAW_SPEECH", "{0}" },
                
                { "DROP_ZONE_INFO", "Tiempo perdido estimado en boxes {0} segundos. Zona de retorno {1}." },
                { "BOX_NOW", "Combustible bajo. Paramos en boxes al final de esta vuelta." },
                { "PIT_EXIT_TRAFFIC", "Cuidado al salir, viene tráfico." },
                { "ZONE_CLEAR", "libre" },
                { "ZONE_1CAR", "un coche" },
                { "ZONE_TRAFFIC", "tráfico denso" },
                { "CALIB_FUEL_REQ", "Necesitamos datos para los cálculos. Pon combustible a 20 litros, sin neumáticos, y haz una parada en boxes." },
                { "CALIB_TYRE_REQ", "Necesitamos datos para los cálculos. Pon neumáticos en ALL4 y haz una parada en boxes." },
                { "CALIB_DT_REQ", "Necesitamos más datos para la estrategia. Por favor realiza un DriveThrough." },
                { "CALIB_SG_REQ", "Necesitamos datos extra para la estrategia. Realiza un Stop and Go." },
                
                { "DIAG_PUSHING", "está empujando bastante fuerte" },
                { "DIAG_FUELSAVING", "está claramente ahorrando gasolina" },
                { "DIAG_TIREWEAR", "está sufriendo con sus neumáticos" },
                { "DIAG_STABLE", "mantiene un ritmo muy estable" },
                { "DIAG_CONSERVING", "está cuidando el coche" },
                { "DIAG_ANALYZING", "analizando ritmo" },

                // Nuove chiavi strategiche e interattive
                { "PIT_EXIT_TRAFFIC_ALERT", "Atención en la salida, nos incorporamos con tráfico! Hay un coche a {0} segundos." },
                { "PIT_EXIT_CLEAR", "Salida de boxes libre, pista despejada, empuja ahora!" },
                { "TARGET_ENTERING_PITS", "Nuestro objetivo {0} entra en boxes ahora." },
                { "TARGET_ENTERING_PITS_OVERCUT", "Nuestro objetivo {0} entra en boxes. El overcut es viable, ¡empuja fuerte en esta vuelta!" },
                { "WET_OPPONENTS_ENTERING_PITS", "Los oponentes están entrando a boxes. Vamos a vigilar su ritmo a la salida." },
                { "RAIN_ALERT", "Humedad al {0}% y presión bajando. Con viento a {1} metros por segundo, se espera lluvia en aproximadamente {2} vueltas." },
                { "TARGET_EXITED_PITS_BEHIND", "Buen trabajo! {0} ha salido de boxes detrás de nosotros." },
                { "TARGET_EXITED_PITS_AHEAD", "{0} ha salido de boxes por delante de nosotros." },
                { "PIT_WINDOW_ALERT", "Ventana de parada abierta. Confirmamos neumáticos y combustible?" },
                { "CONFIRM_INTERACTIVE_FUEL", "Recibido, solo gasolina. Los neumáticos se quedan como están." },
                { "CONFIRM_INTERACTIVE_TYRES", "Recibido, solo neumáticos. Sin repostaje de gasolina." },
                { "CONFIRM_INTERACTIVE_BOTH", "Recibido, parada completa. Neumáticos y gasolina confirmados." },
                { "SANITY_CHECK_PIT_NOT_SET", "Atencin, entramos en boxes pero las opciones no estn configuradas." },
                                { "CONFIRM_JUST_TYRES_NONE", "Perfecto, me alegra saber que los estás controlando." },
                { "PIT_WINDOW_ASK_TYRES", "Ventana de parada abierta. Dime cómo van tus neumáticos." },
                { "CORNER_FL", "delantero izquierdo" },
                { "CORNER_FR", "delantero derecho" },
                { "CORNER_RL", "trasero izquierdo" },
                { "CORNER_RR", "trasero derecho" },
                { "CONFIRM_TYRES_ALL4_0", "Entendido, prepararemos 4 neumáticos nuevos para el próximo stint." },
                { "CONFIRM_TYRES_ALL4_1", "Ok, prepararemos tus neumáticos." },
                { "CONFIRM_TYRES_FRONTS_0", "Entendido, prepararemos 2 delanteros para el próximo stint." },
                { "CONFIRM_TYRES_FRONTS_1", "Ok, cambiaremos los neumáticos delanteros." },
                { "CONFIRM_TYRES_REARS_0", "Entendido, prepararemos 2 traseros para el próximo stint." },
                { "CONFIRM_TYRES_REARS_1", "Ok, cambiaremos los neumáticos traseros." },
                { "CONFIRM_TYRES_LEFT_0", "Entendido, prepararemos 2 izquierdos para el próximo stint." },
                { "CONFIRM_TYRES_LEFT_1", "Ok, cambiaremos los neumáticos izquierdos." },
                { "CONFIRM_TYRES_RIGHT_0", "Entendido, prepararemos 2 derechos para el próximo stint." },
                { "CONFIRM_TYRES_RIGHT_1", "Ok, cambiaremos los neumáticos derechos." },
                { "CONFIRM_TYRES_SINGLE_0", "Entendido, reemplazaremos el neumático {0} para el próximo stint." },
                { "CONFIRM_TYRES_SINGLE_1", "Ok, cambiaremos el neumático {0}." },{ "FUEL_WARNING_LIFT_COAST", "Atención, el combustible es crítico. Si no empezamos a ahorrar ahora, no terminaremos la carrera. Levanta el pie." },
                { "FORMATION_LAP_START", "Ok {0}, mantén tu posición en la vuelta de formación. Intentemos hacer una carrera limpia." },
                { "FORMATION_LAP_GRID", "Ya casi estamos, la bandera verde está a punto de ondear, prepárate." },
                { "CROSSOVER_BOX_WETS", "Los neumáticos de lluvia son ahora {0} segundos más rápidos que nuestros slicks. Se recomienda box para montar Wet." },
                { "CROSSOVER_BOX_SLICKS", "Los neumáticos slick son ahora {0} segundos más rápidos que nuestros neumáticos de lluvia. Se recomienda box para montar Slick." },
                { "CONFIRM_WET", "Neumáticos de lluvia seleccionados." },
                { "CONFIRM_DRY", "Neumáticos slick seleccionados." },
            }},
            { "FR", new Dictionary<string, string> {
                { "TARGET_NO_CAR", "Rien à signaler pour l'instant." },
                                { "REPORT_GAP_0", "{0} est devant nous. L'écart est d'environ {1} secondes." },
                { "REPORT_GAP_1", "On a {0} devant. L'écart est actuellement de {1} secondes." },
                { "REPORT_GAP_2", "{0} est devant nous. L'écart est de l'ordre de {1} secondes." },
                { "REPORT_GAP_3", "On poursuit {0} devant. L'écart est de {1} secondes." },
                { "REPORT_FULL_0", "{0} est devant nous. L'écart est d'environ {1} secondes... et d'après les données je dirais qu'il {2}." },
                { "REPORT_FULL_1", "On a {0} devant. L'écart est actuellement de {1} secondes... et on dirait qu'il {2}." },
                { "REPORT_FULL_2", "{0} est devant nous. L'écart est de l'ordre de {1} secondes... et d'après nos données je dirais qu'il {2}." },
                { "REPORT_FULL_3", "On poursuit {0} devant. L'écart est de {1} secondes... et il semble qu'il {2}." },
                { "REPORT_UNDERCUT", "...on devrait clairement envisager l'undercut ici, on peut passer devant." },
                { "REPORT_NO_UNDERCUT", "...mais c'est trop tôt pour un undercut, continuons de le suivre." },
                { "AUTO_UNDERCUT_ALERT", "Écoute, {0} est dans notre fenêtre d'undercut. Si on s'arrête maintenant, on ressort devant. Penses-y." },
                { "CONFIRM_FULL", "Bien reçu. Confirmé {0} litres et 4 pneus neufs." },
                { "CONFIRM_2TYRES", "Bien reçu. Confirmé {0} litres et 2 pneus neufs." },
                { "CONFIRM_1TYRE", "Bien reçu. Confirmé {0} litres et 1 pneu neuf." },
                { "CONFIRM_FUEL", "Reçu, juste du carburant. On ajoute {0} litres, pas de pneus." },
                { "CONFIRM_PRESS", "Bien reçu, pressions ajustées. J'envoie les données aux mécaniciens." },
                { "CONFIRM_CLEAR", "Ok, options d'arrêt réinitialisées." },
                { "FUEL_TARGET_ALERT", "Consommation trop élevée. Pense à faire du lift and coast." },
                { "FUEL_TARGET_OK", "Bon travail, la gestion du carburant est parfaite." },
                { "RAW_SPEECH", "{0}" },
                
                { "DROP_ZONE_INFO", "Temps perdu estimé aux stands {0} secondes. Zone de retour {1}." },
                { "BOX_NOW", "Carburant bas. Arrêt aux stands à la fin de ce tour." },
                { "PIT_EXIT_TRAFFIC", "Attention en sortant, il y a du trafic." },
                { "ZONE_CLEAR", "libre" },
                { "ZONE_1CAR", "une voiture" },
                { "ZONE_TRAFFIC", "trafic dense" },
                { "CALIB_FUEL_REQ", "Données requises pour les calculs. Ravitaillement à 20 litres, pas de pneus, et fais un arrêt aux stands." },
                { "CALIB_TYRE_REQ", "Données requises pour les calculs. Pneus sur ALL4 et fais un arrêt aux stands." },
                { "CALIB_DT_REQ", "Plus de données requises pour la stratégie. Effectue un DriveThrough s'il te plaît." },
                { "CALIB_SG_REQ", "Données supplémentaires requises. Effectue un Stop and Go." },
                
                { "DIAG_PUSHING", "attaque plutôt fort" },
                { "DIAG_FUELSAVING", "est clairement en train de gérer l'essence" },
                { "DIAG_TIREWEAR", "est en difficulté avec ses pneus" },
                { "DIAG_STABLE", "maintient un rythme très stable" },
                { "DIAG_CONSERVING", "ménage sa monture" },
                { "DIAG_ANALYZING", "analyse du rythme" },

                // Nuove chiavi strategiche e interattive
                { "PIT_EXIT_TRAFFIC_ALERT", "Attention en sortie, nous rentrons dans le trafic ! Une voiture est à {0} secondes." },
                { "PIT_EXIT_CLEAR", "Sortie des stands libre, piste dégagée, attaque maintenant !" },
                { "TARGET_ENTERING_PITS", "Notre cible {0} rentre aux stands maintenant." },
                { "TARGET_ENTERING_PITS_OVERCUT", "Notre cible {0} rentre aux stands. L'overcut est viable, attaque fort dans ce tour!" },
                { "WET_OPPONENTS_ENTERING_PITS", "Les adversaires entrent aux stands. Surveillons leur rythme à la sortie." },
                { "RAIN_ALERT", "Humidité à {0}% et pression en baisse. Avec un vent à {1} mètres par seconde, la pluie est attendue dans environ {2} tours." },
                { "TARGET_EXITED_PITS_BEHIND", "Bon travail ! {0} est ressorti des stands derrière nous." },
                { "TARGET_EXITED_PITS_AHEAD", "{0} est ressorti des stands devant nous." },
                { "PIT_WINDOW_ALERT", "Fenêtre d'arrêt ouverte. Confirmes-tu les pneus et le carburant ?" },
                { "CONFIRM_INTERACTIVE_FUEL", "Bien reçu, seulement du carburant. Les pneus restent comme ça." },
                { "CONFIRM_INTERACTIVE_TYRES", "Bien reçu, seulement les pneus. Pas de ravitaillement." },
                { "CONFIRM_INTERACTIVE_BOTH", "Bien reçu, arrêt complet. Pneus et carburant confirmés." },
                { "SANITY_CHECK_PIT_NOT_SET", "Attention, nous rentrons aux stands mais les options ne sont pas configures." },
                                { "CONFIRM_JUST_TYRES_NONE", "Parfait, ravi de savoir que tu gères ça." },
                { "PIT_WINDOW_ASK_TYRES", "Fenêtre d'arrêt ouverte. Dis-moi comment vont tes pneus." },
                { "CORNER_FL", "avant gauche" },
                { "CORNER_FR", "avant droit" },
                { "CORNER_RL", "arrière gauche" },
                { "CORNER_RR", "arrière droit" },
                { "CONFIRM_TYRES_ALL4_0", "Bien reçu, on prépare 4 pneus neufs pour le prochain stint." },
                { "CONFIRM_TYRES_ALL4_1", "Ok, on prépare tes pneus." },
                { "CONFIRM_TYRES_FRONTS_0", "Bien reçu, on prépare 2 pneus avant pour le prochain stint." },
                { "CONFIRM_TYRES_FRONTS_1", "Ok, on change les pneus avant." },
                { "CONFIRM_TYRES_REARS_0", "Bien reçu, on prépare 2 pneus arrière pour le prochain stint." },
                { "CONFIRM_TYRES_REARS_1", "Ok, on change les pneus arrière." },
                { "CONFIRM_TYRES_LEFT_0", "Bien reçu, on prépare 2 pneus gauche pour le prochain stint." },
                { "CONFIRM_TYRES_LEFT_1", "Ok, on change les pneus gauches." },
                { "CONFIRM_TYRES_RIGHT_0", "Bien reçu, on prépare 2 pneus droit pour le prochain stint." },
                { "CONFIRM_TYRES_RIGHT_1", "Ok, on change les pneus droits." },
                { "CONFIRM_TYRES_SINGLE_0", "Bien reçu, on remplace le pneu {0} pour le prochain stint." },
                { "CONFIRM_TYRES_SINGLE_1", "Ok, on change le pneu {0}." },{ "FUEL_WARNING_LIFT_COAST", "Attention, le carburant est critique. Si on ne commence pas à économiser maintenant, on ne finira pas la course. Lève le pied." },
                { "FORMATION_LAP_START", "Ok {0}, garde ta position dans le tour de formation. Essayons de faire une course propre." },
                { "FORMATION_LAP_GRID", "On y est presque, le drapeau vert va bientôt s'agiter, tiens-toi prêt." },
                { "CROSSOVER_BOX_WETS", "Les pneus pluie sont maintenant {0} secondes plus rapides que nos slicks. Stands recommandés pour les Wet." },
                { "CROSSOVER_BOX_SLICKS", "Les pneus slicks sont maintenant {0} secondes plus rapides que nos pneus pluie. Stands recommandés pour les Slicks." },
                { "CONFIRM_WET", "Pneus pluie sélectionnés." },
                { "CONFIRM_DRY", "Pneus slicks sélectionnés." },
            }},
            { "NL", new Dictionary<string, string> {
                { "TARGET_NO_CAR", "Niets te melden op dit moment." },
                                { "REPORT_GAP_0", "{0} ligt voor ons. Het gat is ongeveer {1} seconden." },
                { "REPORT_GAP_1", "We hebben {0} voor ons. De marge is momenteel {1} seconden." },
                { "REPORT_GAP_2", "{0} rijdt voor ons. Het gat is circa {1} seconden." },
                { "REPORT_GAP_3", "We jagen op {0} voor ons. Het gat is {1} seconden." },
                { "REPORT_FULL_0", "{0} ligt voor ons. Het gat is ongeveer {1} seconden... en te zien aan de data zou ik zeggen dat hij {2}." },
                { "REPORT_FULL_1", "We hebben {0} voor ons. De marge is momenteel {1} seconden... en het lijkt erop dat hij {2}." },
                { "REPORT_FULL_2", "{0} rijdt voor ons. Het gat is circa {1} seconden... en volgens onze gegevens {2}." },
                { "REPORT_FULL_3", "We jagen op {0} voor ons. Het gat is {1} seconden... en het lijkt of hij {2}." },
                { "REPORT_UNDERCUT", "...we moeten hier zeker de undercut overwegen, we kunnen hem pakken." },
                { "REPORT_NO_UNDERCUT", "...maar het is nog wat vroeg voor een undercut, laten we hem voor nu volgen." },
                { "AUTO_UNDERCUT_ALERT", "Luister, {0} zit in onze undercut-window. Als we nu pitten, komen we voor hem. Denk erover na." },
                { "CONFIRM_FULL", "Begrepen. Bevestigd {0} liter en 4 nieuwe banden." },
                { "CONFIRM_2TYRES", "Begrepen. Bevestigd {0} liter and 2 nieuwe banden." },
                { "CONFIRM_1TYRE", "Begrepen. Bevestigd {0} liter and 1 nieuwe banden." },
                { "CONFIRM_FUEL", "Begrepen, alleen brandstof. We vullen {0} liter bij, geen banden." },
                { "CONFIRM_PRESS", "Begrepen, bandenspanning aangepast. Stuur de gegevens naar de crew." },
                { "CONFIRM_CLEAR", "Ok, pit-opties gewist." },
                { "FUEL_TARGET_ALERT", "We verbruiken meer dan ons doel. Denk aan lift and coast." },
                { "FUEL_TARGET_OK", "Goed gedaan, brandstofverbruik zit precies op schema." },
                { "RAW_SPEECH", "{0}" },
                
                { "DROP_ZONE_INFO", "Tijdverlies in de pit is {0} seconden. Terugkeerzone is {1}." },
                { "BOX_NOW", "Brandstof is bijna op. We pitten aan het einde van deze ronde." },
                { "PIT_EXIT_TRAFFIC", "Let op bij het uitgaan, er is verkeer op komst." },
                { "ZONE_CLEAR", "vrij" },
                { "ZONE_1CAR", "één auto" },
                { "ZONE_TRAFFIC", "druk verkeer" },
                { "CALIB_FUEL_REQ", "We hebben data nodig voor de berekeningen. Stel brandstof in op 20 liter, geen banden, en maak een pitstop." },
                { "CALIB_TYRE_REQ", "We hebben data nodig voor de berekeningen. Stel banden in op ALL4 en maak een pitstop." },
                { "CALIB_DT_REQ", "We hebben meer data nodig voor de strategie. Maak alstublieft een drive-through." },
                { "CALIB_SG_REQ", "We hebben extra data nodig voor de strategie. Maak een stop-and-go." },
                
                { "DIAG_PUSHING", "pusht behoorlijk hard" },
                { "DIAG_FUELSAVING", "is duidelijk brandstof aan het sparen" },
                { "DIAG_TIREWEAR", "heeft problemen met zijn banden" },
                { "DIAG_STABLE", "houdt een constant tempo aan" },
                { "DIAG_CONSERVING", "spaart zijn auto" },
                { "DIAG_ANALYZING", "tempo analyseren" },

                // Nuove chiavi strategiche e interattive
                { "PIT_EXIT_TRAFFIC_ALERT", "Let op bij het uitrijden, we komen in verkeer terecht! Er is een auto op {0} seconden." },
                { "PIT_EXIT_CLEAR", "Pit-exit is vrij, lege baan, pushen nu!" },
                { "TARGET_ENTERING_PITS", "Ons doel {0} gaat nu pitten." },
                { "TARGET_ENTERING_PITS_OVERCUT", "Ons doel {0} gaat pitten. Overcut is mogelijk, push hard in deze ronde!" },
                { "WET_OPPONENTS_ENTERING_PITS", "De tegenstanders komen de pits in. Laten we hun tempo bij het uitkomen in de gaten houden." },
                { "RAIN_ALERT", "Luchtvochtigheid op {0}% en druk daalt. Met wind op {1} meter per seconde, wordt regen verwacht over ongeveer {2} ronden." },
                { "TARGET_EXITED_PITS_BEHIND", "Goed gedaan! {0} komt achter ons de pit uit." },
                { "TARGET_EXITED_PITS_AHEAD", "{0} komt voor ons de pit uit." },
                { "PIT_WINDOW_ALERT", "Pit-window is open. Bevestigen we banden en brandstof?" },
                { "CONFIRM_INTERACTIVE_FUEL", "Begrepen, alleen brandstof. Banden blijven hetzelfde." },
                { "CONFIRM_INTERACTIVE_TYRES", "Begrepen, alleen banden. Geen brandstof erbij." },
                { "CONFIRM_INTERACTIVE_BOTH", "Begrepen, volledige stop. Banden en brandstof bevestigd." },
                { "SANITY_CHECK_PIT_NOT_SET", "Let op, we gaan de pit in maar de opties zijn niet ingesteld." },
                                { "CONFIRM_JUST_TYRES_NONE", "Perfect, goed om te horen dat je het beheert." },
                { "PIT_WINDOW_ASK_TYRES", "Pit-window is open. Laat me weten hoe je banden zijn." },
                { "CORNER_FL", "linksvoor" },
                { "CORNER_FR", "rechtsvoor" },
                { "CORNER_RL", "linksachter" },
                { "CORNER_RR", "rechtsachter" },
                { "CONFIRM_TYRES_ALL4_0", "Begrepen, we bereiden 4 nieuwe banden voor de volgende stint." },
                { "CONFIRM_TYRES_ALL4_1", "Ok, we maken je banden klaar." },
                { "CONFIRM_TYRES_FRONTS_0", "Begrepen, we bereiden 2 voorbanden voor de volgende stint." },
                { "CONFIRM_TYRES_FRONTS_1", "Ok, we wisselen de voorbanden." },
                { "CONFIRM_TYRES_REARS_0", "Begrepen, we bereiden 2 achterbanden voor de volgende stint." },
                { "CONFIRM_TYRES_REARS_1", "Ok, we wisselen de achterbanden." },
                { "CONFIRM_TYRES_LEFT_0", "Begrepen, we bereiden 2 linkerbanden voor de volgende stint." },
                { "CONFIRM_TYRES_LEFT_1", "Ok, we wisselen de linkerbanden." },
                { "CONFIRM_TYRES_RIGHT_0", "Begrepen, we bereiden 2 rechterbanden voor de volgende stint." },
                { "CONFIRM_TYRES_RIGHT_1", "Ok, we wisselen de rechterbanden." },
                { "CONFIRM_TYRES_SINGLE_0", "Begrepen, we vervangen de {0} band voor de volgende stint." },
                { "CONFIRM_TYRES_SINGLE_1", "Ok, we wisselen de {0} band." },{ "FUEL_WARNING_LIFT_COAST", "Let op, brandstof is kritiek. Als we nu niet gaan sparen, halen we de finish niet. Lift and coast." },
                { "FORMATION_LAP_START", "Ok {0}, behoud je positie in de formatieronde. Laten we er een schone race van maken." },
                { "FORMATION_LAP_GRID", "Bijna daar, de groene vlag zwaait zo, maak je klaar." },
                { "CROSSOVER_BOX_WETS", "Regenbanden zijn nu {0} seconden sneller dan onze slicks. Pitstop aanbevolen voor Wets." },
                { "CROSSOVER_BOX_SLICKS", "Slicks zijn nu {0} seconden sneller dan onze regenbanden. Pitstop aanbevolen voor Slicks." },
                { "CONFIRM_WET", "Regenbanden geselecteerd." },
                { "CONFIRM_DRY", "Slicks geselecteerd." },
            }},
            { "PT", new Dictionary<string, string> {
                { "TARGET_NO_CAR", "Nada a declarar no momento." },
                                { "REPORT_GAP_0", "{0} está à nossa frente. A distância é de cerca de {1} segundos." },
                { "REPORT_GAP_1", "Temos o {0} na frente. A margem é atualmente de {1} segundos." },
                { "REPORT_GAP_2", "{0} está na nossa frente. A distância é de aproximadamente {1} segundos." },
                { "REPORT_GAP_3", "Perseguindo {0} à frente. A distância é de {1} segundos." },
                { "REPORT_FULL_0", "{0} está à nossa frente. A distância é de cerca de {1} segundos... e pelos dados eu diria que {2}." },
                { "REPORT_FULL_1", "Temos o {0} na frente. A margem é atualmente de {1} segundos... e parece que {2}." },
                { "REPORT_FULL_2", "{0} está na nossa frente. A distância é de aproximadamente {1} segundos... e pelos nossos dados eu diria que {2}." },
                { "REPORT_FULL_3", "Perseguindo {0} à frente. A distância é de {1} segundos... e parece que está {2}." },
                { "REPORT_UNDERCUT", "...definitivamente deveríamos considerar o undercut aqui, podemos passar." },
                { "REPORT_NO_UNDERCUT", "...mas ainda é cedo para um undercut, vamos segui-lo por enquanto." },
                { "AUTO_UNDERCUT_ALERT", "Olha, {0} está na nossa janela de undercut. Se pararmos agora saímos na frente. Pense nisso." },
                { "CONFIRM_FULL", "Entendido. Confirmados {0} litros e 4 pneus novos." },
                { "CONFIRM_2TYRES", "Entendido. Confirmados {0} litros e 2 pneus novos." },
                { "CONFIRM_1TYRE", "Entendido. Confirmados {0} litros e 1 pneu novo." },
                { "CONFIRM_FUEL", "Entendido, apenas combustível. Adicionando {0} litros, pneus continuam os mesmos." },
                { "CONFIRM_PRESS", "Entendido, pressões ajustadas. Enviando os dados para os mecânicos." },
                { "CONFIRM_CLEAR", "Ok, opções de pit stop redefinidas." },
                { "FUEL_TARGET_ALERT", "Consumo acima do nosso alvo. Lembre-se de levantar o pé antes." },
                { "FUEL_TARGET_OK", "Bom trabalho, a gestão de combustível está perfeita." },
                { "RAW_SPEECH", "{0}" },
                
                { "DROP_ZONE_INFO", "Tempo perdido estimado no box {0} segundos. Zona de retorno {1}." },
                { "BOX_NOW", "Combustível no fim. Paramos no box no final desta volta." },
                { "PIT_EXIT_TRAFFIC", "Cuidado ao sair, vem tráfego aí." },
                { "ZONE_CLEAR", "livre" },
                { "ZONE_1CAR", "um carro" },
                { "ZONE_TRAFFIC", "tráfego intenso" },
                { "CALIB_FUEL_REQ", "Precisamos de dados para os cálculos. Ajuste combustível para 20 litros, sem pneus, e faça um pit stop." },
                { "CALIB_TYRE_REQ", "Precisamos de dados para os cálculos. Ajuste pneus para ALL4 e faça um pit stop." },
                { "CALIB_DT_REQ", "Precisamos de mais dados para a estratégia. Por favor realize um DriveThrough." },
                { "CALIB_SG_REQ", "Precisamos de dados extras para a estratégia. Realize um Stop and Go." },
                
                { "DIAG_PUSHING", "está forçando bastante" },
                { "DIAG_FUELSAVING", "está claramente economizando combustível" },
                { "DIAG_TIREWEAR", "está com problemas nos pneus" },
                { "DIAG_STABLE", "mantém um ritmo muito estável" },
                { "DIAG_CONSERVING", "está poupando o carro" },
                { "DIAG_ANALYZING", "analisando ritmo" },

                // Nuove chiavi strategiche e interattive
                { "PIT_EXIT_TRAFFIC_ALERT", "Cuidado na saída, estamos voltando com tráfego! Tem um carro a {0} segundos." },
                { "PIT_EXIT_CLEAR", "Saída de box livre, pista limpa, acelera agora!" },
                { "TARGET_ENTERING_PITS", "Nosso alvo {0} está entrando no box agora." },
                { "TARGET_ENTERING_PITS_OVERCUT", "O nosso alvo {0} está a entrar nas boxes. O overcut é viável, empurra forte nesta volta!" },
                { "WET_OPPONENTS_ENTERING_PITS", "Os adversários estão a entrar nas boxes. Vamos monitorizar o ritmo deles na saída." },
                { "RAIN_ALERT", "Humidade a {0}% e pressão a descer. Com vento a {1} metros por segundo, a chuva é esperada em cerca de {2} voltas." },
                { "TARGET_EXITED_PITS_BEHIND", "Bom trabalho! {0} saiu do box atrás de nós." },
                { "TARGET_EXITED_PITS_AHEAD", "{0} saiu do box na nossa frente." },
                { "PIT_WINDOW_ALERT", "Janela de box aberta. Confirmamos pneus e combustível?" },
                { "CONFIRM_INTERACTIVE_FUEL", "Entendido, apenas combustível. Os pneus continuam os mesmos." },
                { "CONFIRM_INTERACTIVE_TYRES", "Entendido, apenas pneus. Sem combustível." },
                { "CONFIRM_INTERACTIVE_BOTH", "Entendido, parada completa. Pneus e combustível confirmados." },
                { "SANITY_CHECK_PIT_NOT_SET", "Ateno, estamos entrando no box mas as opes no esto configuradas." },
                                { "CONFIRM_JUST_TYRES_NONE", "Perfeito, que bom saber que você está gerenciando." },
                { "PIT_WINDOW_ASK_TYRES", "Janela de box aberta. Diga-me como estão os pneus." },
                { "CORNER_FL", "dianteiro esquerdo" },
                { "CORNER_FR", "dianteiro direito" },
                { "CORNER_RL", "traseiro esquerdo" },
                { "CORNER_RR", "traseiro direito" },
                { "CONFIRM_TYRES_ALL4_0", "Entendido, vamos preparar 4 pneus novos para o próximo stint." },
                { "CONFIRM_TYRES_ALL4_1", "Ok, vamos deixar seus pneus prontos." },
                { "CONFIRM_TYRES_FRONTS_0", "Entendido, vamos preparar 2 dianteiros para o próximo stint." },
                { "CONFIRM_TYRES_FRONTS_1", "Ok, vamos trocar os pneus dianteiros." },
                { "CONFIRM_TYRES_REARS_0", "Entendido, vamos preparar 2 traseiros para o próximo stint." },
                { "CONFIRM_TYRES_REARS_1", "Ok, vamos trocar os pneus traseiros." },
                { "CONFIRM_TYRES_LEFT_0", "Entendido, vamos preparar 2 esquerdos para o próximo stint." },
                { "CONFIRM_TYRES_LEFT_1", "Ok, vamos trocar os pneus esquerdos." },
                { "CONFIRM_TYRES_RIGHT_0", "Entendido, vamos preparar 2 direitos para o próximo stint." },
                { "CONFIRM_TYRES_RIGHT_1", "Ok, vamos trocar os pneus direitos." },
                { "CONFIRM_TYRES_SINGLE_0", "Entendido, vamos substituir o pneu {0} para o próximo stint." },
                { "CONFIRM_TYRES_SINGLE_1", "Ok, vamos trocar o pneu {0}." },{ "FUEL_WARNING_LIFT_COAST", "Atenção, o combustível é crítico. Se não começarmos a economizar agora, não terminaremos a corrida. Levante o pé." },
                { "FORMATION_LAP_START", "Ok {0}, mantenha a sua posição na volta de apresentação. Vamos fazer uma corrida limpa." },
                { "FORMATION_LAP_GRID", "Quase lá, a bandeira verde está prestes a acenar, prepare-se." },
                { "CROSSOVER_BOX_WETS", "Os pneus de chuva são agora {0} segundos mais rápidos do que os nossos slicks. Box recomendado para Wet." },
                { "CROSSOVER_BOX_SLICKS", "Os pneus slicks são agora {0} segundos mais rápidos do que os nossos pneus de chuva. Box recomendado para Slick." },
                { "CONFIRM_WET", "Pneus de chuva selecionados." },
                { "CONFIRM_DRY", "Pneus slicks selecionados." },
            }}
        };

        public static string GetPhrase(string languageKey, string messageKey, params object[] args)
        {
            if (!Dictionary.ContainsKey(languageKey)) languageKey = "EN";
            if (Dictionary[languageKey].TryGetValue(messageKey, out string format))
            {
                if (args != null && args.Length > 0) return string.Format(format, args);
                return format;
            }
            return "";
        }
    }
}